"""add employee profile fields

Revision ID: 7c90e71b4f6e
Revises: cd9874b86aa4
Create Date: 2026-06-17 17:50:18.935885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c90e71b4f6e'
down_revision: Union[str, Sequence[str], None] = 'cd9874b86aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
