"""new fields added in user and new tables added

Revision ID: 870281a16eac
Revises: 7c90e71b4f6e
Create Date: 2026-06-17 20:08:21.413184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870281a16eac'
down_revision: Union[str, Sequence[str], None] = '7c90e71b4f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('joining_date', sa.String(length=12), nullable=True),
    sa.Column('reporting_manager', sa.String(length=12), nullable=True),
    sa.Column('salary', sa.String(length=12), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.String(length=50), nullable=True),
    sa.Column('target', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_logout', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_logout')
    op.drop_column('users', 'last_login')
    op.drop_table('employee_profiles')
    # ### end Alembic commands ###
