"""prospect table added

Revision ID: a85d29c6a1bc
Revises: 161c9b32bb91
Create Date: 2026-06-18 00:40:41.761186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a85d29c6a1bc'
down_revision: Union[str, Sequence[str], None] = '161c9b32bb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── Create the Postgres enum type explicitly first ──────────────────
    prospect_stage_enum = postgresql.ENUM(
        'new', 'contacted', 'negotiation', 'won', 'lost',
        name='prospectstage'
    )
    prospect_stage_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.create_table('incentive_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('advance', 'installment', 'final', name='paymenttype'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_by_id'), 'payments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_payments_prospect_id'), 'payments', ['prospect_id'], unique=False)
    op.create_table('prospect_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('aadhar', 'passport_photo', 'sslc', 'plus_two_degree', 'agreement', name='documenttype'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_documents_prospect_id'), 'prospect_documents', ['prospect_id'], unique=False)
    op.add_column('prospects', sa.Column('prospect_id', sa.String(length=20), nullable=False))
    op.add_column('prospects', sa.Column('password', sa.String(length=50), nullable=True))
    op.add_column('prospects', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('prospects', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('prospects', sa.Column('father_name', sa.String(length=255), nullable=True))
    op.add_column('prospects', sa.Column('mother_name', sa.String(length=255), nullable=True))
    op.add_column('prospects', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('prospects', sa.Column('specialization', sa.String(length=255), nullable=True))
    op.add_column('prospects', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('prospects', sa.Column('estimated_deal_value', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('prospects', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('prospects', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prospects', sa.Column('notes', sa.Text(), nullable=True))

    op.add_column(
        'prospects',
        sa.Column(
            'stage',
            postgresql.ENUM(
                'new', 'contacted', 'negotiation', 'won', 'lost',
                name='prospectstage',
                create_type=False,   # the type already exists from the line above
            ),
            nullable=False,
            server_default='new',     # required: prospects already has rows (or might), NOT NULL needs a default to backfill
        )
    )
    op.add_column('prospects', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.add_column('prospects', sa.Column('exam_attended', sa.Boolean(), nullable=False))
    op.add_column('prospects', sa.Column('exam_certified', sa.Boolean(), nullable=False))
    op.add_column('prospects', sa.Column('sheets_synced', sa.Boolean(), nullable=False))
    op.add_column('prospects', sa.Column('sheets_row_id', sa.String(length=50), nullable=True))
    op.alter_column('prospects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_prospects_assigned_to_id'), 'prospects', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=False)
    op.create_index(op.f('ix_prospects_prospect_id'), 'prospects', ['prospect_id'], unique=True)
    op.create_index(op.f('ix_prospects_stage'), 'prospects', ['stage'], unique=False)
    op.create_foreign_key(None, 'prospects', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'prospects', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospects', type_='foreignkey')
    op.drop_constraint(None, 'prospects', type_='foreignkey')
    op.drop_index(op.f('ix_prospects_stage'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_prospect_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_assigned_to_id'), table_name='prospects')
    op.alter_column('prospects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('prospects', 'sheets_row_id')
    op.drop_column('prospects', 'sheets_synced')
    op.drop_column('prospects', 'exam_certified')
    op.drop_column('prospects', 'exam_attended')
    op.drop_column('prospects', 'assigned_to_id')
    op.drop_column('prospects', 'stage')
    op.drop_column('prospects', 'notes')
    op.drop_column('prospects', 'delivery_date')
    op.drop_column('prospects', 'delivery_address')
    op.drop_column('prospects', 'estimated_deal_value')
    op.drop_column('prospects', 'address')
    op.drop_column('prospects', 'specialization')
    op.drop_column('prospects', 'course_id')
    op.drop_column('prospects', 'mother_name')
    op.drop_column('prospects', 'father_name')
    op.drop_column('prospects', 'phone')
    op.drop_column('prospects', 'email')
    op.drop_column('prospects', 'password')
    op.drop_column('prospects', 'prospect_id')
    op.drop_index(op.f('ix_prospect_documents_prospect_id'), table_name='prospect_documents')
    op.drop_table('prospect_documents')
    op.drop_index(op.f('ix_payments_prospect_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_by_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_table('incentive_slabs')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    # Drop the enum type last, after nothing references it anymore
    prospect_stage_enum = postgresql.ENUM(
        'new', 'contacted', 'negotiation', 'won', 'lost',
        name='prospectstage'
    )
    prospect_stage_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
